on: push
name: make all
jobs:
  makeall:
    name: make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make all
        uses: docker://golang:latest
        with:
          entrypoint: bash
          args: -c "go get honnef.co/go/tools/cmd/staticcheck && git config --global --add safe.directory /github/workspace && make all"
